USE [qds16172939_db]
GO

/****** Object:  Table [dbo].[z_fcname]    Script Date: 2017/11/25 16:26:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[z_fcname](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[部门名称] [nchar](50) NULL,
	[删除] [decimal](1, 0) NULL CONSTRAINT [DF_z_fcname_删除]  DEFAULT ((0)),
 CONSTRAINT [PK_z_fcname] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

